[package]
name = "lis2mdl"
version = "0.1.0"
authors = ["Stefan Lüthi <stefan.luethi@outlook.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.3"
num_enum = { version = "~0.5", default-features = false }

[dependencies.micromath]
version = "1"
features = ["vector"]

[dev-dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
panic-halt = "0.2.0"
